strategy:
  type: copy
  volume_ratio: 0.1
  target:
    driver: rubykube
    market: 'rvgeth'
    host: "https://www.rvgtrade.io"
    key: "0de19b3c-0d48-46c5-bcdd-3129167a6995"
    secret: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyQjgyT3dFMnNtVTNOQ2R3bjBkWQpvZnpoYWJ2b3QxVkJ4UEdMYWhwZWRUU0xLWmFGcndKV3FQOXlrSGpzSUdnZzEzZFVyV1BFQlpKSFlqdjF2cGpjCmpjL0tlUXl4YU9wWGZtMC9LdHpIV2d4UytYaU45Y0pqaVJjdnhHUUVZd3U5cFVMS203Ui9RV2VDNGp1ODJzT0kKSU9HbTV1Q2dMby8vRVpBUk1LcjdUMzJtUG5WaUZVRk1ENkZxMldEc1l4YmxObDJVa2h3WUt3eUZ0QWVLUUY3Nwp3S0l6N285NDV1aSs1ckJldGpxY0gybE5LWXJJRmZWZU93OU50anBnS2ZrQzMwTTBneFlLN1dVaUJGeHVWc05KCm1YaUwwZ0hLbG91bzJseHlJb1FwRUJTUFdLRW5MTjNPNGNwQk55NUp6dUhTUHhBNU9TWGNYNjN2NzVieWlmRDUKb3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
    private: "eyJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1Njc3MDMyMjksImV4cCI6MTU2NzcxNzYyOSwic3ViIjoic2Vzc2lvbiIsImlzcyI6ImJhcm9uZyIsImF1ZCI6WyJwZWF0aW8iLCJiYXJvbmciXSwianRpIjoiRjUyM0Y1OEFGMTNCRTE5NkRDNEFCQzgxIiwidWlkIjoiSURCNzhBRTk1MUE1IiwiZW1haWwiOiJwaHVvbmcxNzg4OUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJsZXZlbCI6MSwic3RhdGUiOiJhY3RpdmUifQ.P-Wd_XXPXryUQD24mG1IkhDIzDBfCNAzXGTMLouicE22V6FxynrQ4cJ4Z0IQ33XIFACiNl9QLuB5okM1x6RhlnqzJ2evgCLbVAf4XzG_syOBhidoR3AFLiRJLlZJX8hZ4di6rV6JXd3RnrE32kX1ygCTHJVZg-CvRCQOvYFy5k5OiHF-jXVNPQTG6Hxb8DFAlTOFUIjYEnmImq9UCZPsdFByZY9bA2CkzeeZh7-1DqzDXIa9cjd-M1q0Hnrlr-Efu4-8aAt3-44UnGOOhJSnF0gzHd1GKeR5Oqhc_GNud68hhjSODepWXLXMTKLvsQDL-b76S5l9CmCPexrgAsV3rg"
    rate_limit: 1
  sources:
    - driver: binance
      market: 'ALGOUSDT'
      host: "api.binance.com"
      key: "S5TpdJIY54So5u2r9pasj4cE6wxOxD1ptci3xywMq5ao9h5vSA8chq7FiFSgkFAg"
      secret: "1xI841d2DHY7w2Y76zZ2J5zEKHDfjeo7Cbr1sQU7CHrdNY15RNhsW0eHDgc9Wp9h"
      rate_limit: 1
